BugMgr/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # v1/ ---> app为web的urls中
    path('v1/', include('web.urls')),
]

apps/web/models.py
from django.db import models


# Create your models here.

# app_userinfo
class UserInfo(models.Model):
    login_name = models.CharField(verbose_name="登录名",   max_length=100, db_index=True)  # 登陆名字段
    username = models.CharField(verbose_name="姓名", max_length=100)  # 姓名
    email = models.EmailField(verbose_name="邮箱", max_length=200)  # 邮箱地址
    mobile_phone = models.CharField(verbose_name="手机号码", max_length=100)  # 手机号码
    password = models.CharField(verbose_name="密码", max_length=500)  # 密码

    class Meta:
        managed = True

    def __str__(self):
        return "登陆名：%s\t用户名：%s" % (self.login_name, self.username)

apps/web/forms/account.py
# 引入django中表单的模块
from django import forms
# 引入models中的类
from web.models import UserInfo
# 引入异常
from django.core.exceptions import ValidationError
# 引入正则模块
import re
# 引入settings
from django.conf import settings
# 引入随机值函数
import random
# 引入发腾讯短信接口
from utils.tencent.sms import send_sms_single
# 引入Redis模块
from django_redis import get_redis_connection
# 引入md5加密模块
from utils import encrypt
# 引入Q查询
from django.db.models import Q

"""

#  新建一个用户注册的表单
class RegisterForm(forms.Form):
    # 登录名，用户名，密码，重复密码，邮箱，手机号码，验证
    login_name = forms.CharField(label="登录名", widget=forms.TextInput(attrs={'class': 'form-control',
                                                                            'placeholder': '请输入登录名'
                                                                            }))
    username = forms.CharField(label="用户名", widget=forms.TextInput(attrs={'class': 'form-control',
                                                                          'placeholder': '请输入用户名'
                                                                          }))
    password = forms.CharField(label="密码", widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': '请输入邮箱'
                                                                             }))
    re_password = forms.CharField(label="确认密码", widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                  'placeholder': '请输入邮箱'
                                                                                  }))
    email = forms.EmailField(label="邮箱", widget=forms.TextInput(attrs={'class': 'form-control',
                                                                       'placeholder': '请输入邮箱'
                                                                       }))
    mobile_phone = forms.CharField(label="手机号码",
                                   widget=forms.TextInput(attrs={'class': 'form-control',
                                                                 'placeholder': '请输入手机号码'
                                                                 })
                                   )
    code = forms.CharField(label="验证码", widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'placeholder': '请输入验证码'
                                                                      }))
"""


# 用户注册表单
class RegisterForm(forms.ModelForm):
    # 添加字段
    password = forms.CharField(label="密码", required=True, widget=forms.PasswordInput())
    re_password = forms.CharField(label="确认密码", required=True, widget=forms.PasswordInput())
    code = forms.CharField(label="验证码", required=True, )

    class Meta:
        model = UserInfo
        fields = ['login_name', 'username', 'password', 're_password', 'email', 'mobile_phone', 'code']

    # 重新类的初始化函数
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 为当前所有字段添加属性
        for name, field in self.fields.items():
            # 添加class: form-control
            field.widget.attrs['class'] = "form-control"
            # 添加placeholder属性
            field.widget.attrs['placeholder'] = "请输入{}".format(field.label)

    # ===================钩子函数实现=======================
    def clean_login_name(self):
        # 取出值
        login_name = self.cleaned_data['login_name']
        # 判断在数据库中是否存在
        is_exists = UserInfo.objects.filter(login_name=login_name).exists()
        if is_exists:
            raise ValidationError("登陆名已存在！")

        # 返回
        return login_name

    def clean_password(self):
        # 取出password -- 明文
        password = self.cleaned_data['password']
        # 长度是否介于8-20
        if len(password) < 8 or len(password) > 20:
            raise ValidationError("密码长度必须介于8-20位！")
        # 返回
        return encrypt.md5(password)

    def clean_re_password(self):
        # 取出确认密码 --- 明文
        re_password = self.cleaned_data['re_password']
        password = self.cleaned_data['password']

        encrypt_re_password = encrypt.md5(re_password)
        # 判断两次密码是否一致
        if password != encrypt_re_password:
            raise ValidationError("两次密码不一致，请重新输入！")
        # 返回
        return re_password

    def clean_email(self):
        # 取出邮箱
        email = self.cleaned_data['email']
        # 判断在数据库是否存在
        is_exists = UserInfo.objects.filter(email=email).exists()
        if is_exists:
            raise ValidationError("邮箱地址已存在！")
        return email

    def clean_mobile_phone(self):
        # 取出手机号码
        mobile_phone = self.cleaned_data['mobile_phone']
        # ===正则表达式===
        match_res = re.match(r'^[1][345789]\d{9}$', mobile_phone)
        # 如果不匹配
        if not match_res:
            raise ValidationError("手机号码不符合规范！")
        # 判断在数据库是否存在
        is_exists = UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
        if is_exists:
            raise ValidationError("手机号码已存在！")
        # 返回
        return mobile_phone

    def clean_code(self):
        # 取出验证码
        code = self.cleaned_data['code']
        mobile_phone = self.cleaned_data['mobile_phone']
        # 在redis中取出code
        conn = get_redis_connection()
        # 取出code
        redis_code = conn.get(mobile_phone)
        # ===判断redis_code是否存在
        if not redis_code:
            raise ValidationError("验证码已过期!请重新发送！")
        # =====判断验证码一致-----
        if code.strip() != redis_code.decode('utf-8'):
            raise ValidationError("输入的验证码错误！")
        # 返回
        return code


# 登陆表单
class LoginForm(forms.Form):
    login_name = forms.CharField(label="用户名/邮箱/手机号码", required=True)
    password = forms.CharField(label="密码", widget=forms.PasswordInput(render_value=True))
    image_code = forms.CharField(label="图片验证码")

    # 重新类的初始化函数
    def __init__(self, request, *args, **kwargs):
        # 使用父类初始化
        super().__init__(*args, **kwargs)
        # 接收views中传递来的request
        self.request = request
        # 为当前所有字段添加属性
        for name, field in self.fields.items():
            # 添加class: form-control
            field.widget.attrs['class'] = "form-control"
            # 添加placeholder属性
            field.widget.attrs['placeholder'] = "请输入{}".format(field.label)

    # ================钩子函数======================
    def clean_password(self):
        # 获取密码
        password = self.cleaned_data['password']
        # 返回加密的密码
        return encrypt.md5(password)

    def clean_image_code(self):
        # 获取输入的code
        image_code = self.cleaned_data['image_code']
        # 获取用户名和密码
        login_name = self.cleaned_data['login_name']
        password = self.cleaned_data['password']

        # 校验图片验证码输入的是否正确
        session_code = self.request.session.get('image_code')
        # 判断是否有验证码
        if not session_code:
            raise ValidationError("验证码已过期！请重新获取！")
        # 判断验证码是否正确
        if image_code.strip().upper() != session_code.strip().upper():
            raise ValidationError("验证码输入错误！")

        # ==================== 身份验证 =================
        # user_object = UserInfo.objects.filter(
        #     Q(login_name=login_name) | Q(email=login_name) | Q(mobile_phone=login_name)).filter(
        #     password=password).first()
        #
        # # 判断是否有对象
        # if not user_object:
        #     raise ValidationError("用户名或者密码错误！")

        # 返回
        return image_code


# 手机验证码登录表单
class SmsLoginForm(forms.Form):
    mobile_phone = forms.CharField(label="手机号码")
    code = forms.CharField(label="验证码")

    # 重新类的初始化函数
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 为当前所有字段添加属性
        for name, field in self.fields.items():
            # 添加class: form-control
            field.widget.attrs['class'] = "form-control"
            # 添加placeholder属性
            field.widget.attrs['placeholder'] = "请输入{}".format(field.label)

    # ===================钩子函数 ================
    def clean_mobile_phone(self):
        # 获取手机号码
        mobile_phone = self.cleaned_data['mobile_phone']
        # 判断是否存在
        user_object = UserInfo.objects.filter(mobile_phone=mobile_phone).first()
        if not user_object:
            raise ValidationError("手机号码不存在，请先注册!")
        # 返回
        return user_object

    def clean_code(self):
        # 获取验证码
        code = self.cleaned_data['code']
        user_object = self.cleaned_data['mobile_phone']
        # 判断
        if not user_object:
            return code
        # ===========验证码校验=================
        conn = get_redis_connection()
        redis_code = conn.get(user_object.mobile_phone)
        # 如果没有取到
        if not redis_code:
            raise ValidationError("验证码失效或者未发送，请重新发送！")
        # 把验证码转为字符串
        redis_code_str = redis_code.decode("utf-8")
        # 比较
        if code.strip() != redis_code_str:
            raise ValidationError("验证码错误！重新输入！")

        # 返回
        return code


# 重置密码的表单
class ResetPasswordForm(forms.Form):
    mobile_phone = forms.CharField(label="手机号码", required=True)
    code = forms.CharField(label="验证码", required=True)
    password = forms.CharField(label="密码", required=True, widget=forms.PasswordInput())
    re_password = forms.CharField(label="重复密码", required=True, widget=forms.PasswordInput())

    # 重新类的初始化函数
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 为当前所有字段添加属性
        for name, field in self.fields.items():
            # 添加class: form-control
            field.widget.attrs['class'] = "form-control"
            # 添加placeholder属性
            field.widget.attrs['placeholder'] = "请输入{}".format(field.label)

    # ========================= 钩子函数=============================
    def clean_mobile_phone(self):
        # 获取手机号码
        mobile_phone = self.cleaned_data.get('mobile_phone')
        # ===正则表达式===

apps/web/views/home.py
"""
 首页相关的views
"""
# 引入render
from django.shortcuts import render
# 引入models中的对象
from web.models import UserInfo


def index(request):
    """首页"""
    # 加载页面
    return render(request, 'home.html')

apps/web/templates/demo.html
{% extends 'layout/base01.html' %}


<!--
继承模板后需要修改的地方:
1. 标题
2. 内容 --- 表单
3. 样式 ---- CSS
4. Script --- 事件
-->

<!-- 添加自己页面的内容 -->
<!-- 修改标题 -->
{% block title %}
    用户注册
{% endblock %}

<!-- 修改样式 -->
{% block css %}
    <style>
        #regForm {
            width: 500px;
            margin: 40px auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            padding: 30px;
            border-radius: 20px;
        }

        .error_msg {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

<!-- 修改内容 -->
{% block content %}
    <form id="regForm" action="{% url 'demo' %}" method="post" novalidate>
        {% csrf_token %}
        <h1 style="text-align: center">用户测试表单</h1>
        <hr>
        <!-- 通过form对象快速生成表单 -->
        {% for field in form %}

            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }} <!-- 添加一个属性 class="form-control" -->
                <span class="error_msg"></span>
            </div>

        {% endfor %}
        <div style="margin-top: 30px">
            <input id="btnSubmit" type="button" class="btn btn-primary" style="width: 120px" value="提交">
            <a href="{% url 'login' %}" style="margin-left: 20px">账号登陆？</a>
            <a href="{% url 'sms_login' %}" style="margin-left: 10px">验证码登陆？</a>
            <a href="{% url 'resetpassword' %}" style="margin-left: 10px">忘记密码？</a>
        </div>

    </form>
{% endblock %}

<!-- 修改Script -->
{% block js %}
    <script>
        // 入口函数
        $(function () {
            // # 响应提交按钮！
            $('#btnSubmit').click(function () {
                //===Ajax=====
                $.ajax({
                    url: "{% url 'demo' %}",
                    method: 'post',
                    data: $('#regForm').serialize(),
                    dataType: 'json',
                    success: function (res) {
                        console.log(res);
                        if(!res.status){
                            $.each(res.errors, function (key,value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            });
        });

    </script>
{% endblock %}

apps/web/templates/home.html
{% extends 'layout/base01.html' %}
{% load static %}

{% block title %}
    首页
{% endblock %}

{% block css %}
    <style>
        img{
            width: 100%;
        }
    </style>
{% endblock %}


{% block content %}
    <img src="{% static 'image/index/index-1.png' %}" alt="image1">
    <img src="{% static 'image/index/index-2.png' %}" alt="image2">
    <img src="{% static 'image/index/index-3.png' %}" alt="image3">
    <img src="{% static 'image/index/index-4.png' %}" alt="image4">
{% endblock %}


{% block js %}
{% endblock %}

apps/web/templates/register.html
{% extends 'layout/base01.html' %}


<!--
继承模板后需要修改的地方:
1. 标题
2. 内容 --- 表单
3. 样式 ---- CSS
4. Script --- 事件
-->

<!-- 添加自己页面的内容 -->
<!-- 修改标题 -->
{% block title %}
    用户注册
{% endblock %}

<!-- 修改样式 -->
{% block css %}
    <style>
        #regForm {
            width: 500px;
            margin: 40px auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            padding: 30px;
            border-radius: 20px;
        }
        .error_msg {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

<!-- 修改内容 -->
{% block content %}
    <form id="regForm">
        {% csrf_token %}
        <h1 style="text-align: center">用户注册</h1>
        <hr>
        <!-- 通过form对象快速生成表单 -->
        {% for field in form %}
            <!--判断是不是验证码的字段 -->
            {% if field.name == 'code' %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    <div class="clearfix">
                        <div class="col-md-6" style="padding-left: 0">
                            {{ field }}
                            <span class="error_msg"></span>
                        </div>
                        <div class="col-md-6">
                            <input type="button" class="btn btn-success" id="btnSMS" value="点击获取验证码"
                                   style="width:200px">
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }} <!-- 添加一个属性 class="form-control" -->
                    <span class="error_msg"></span>
                </div>
            {% endif %}
        {% endfor %}
        <div style="margin-top: 30px">
            <input type="button" id="btnSubmit" class="btn btn-primary" style="width: 120px" value="注册">
            <a href="{% url 'login' %}" style="margin-left: 20px">账号登陆？</a>
            <a href="{% url 'sms_login' %}" style="margin-left: 10px">验证码登陆？</a>
            <a href="{% url 'resetpassword' %}" style="margin-left: 10px">忘记密码？</a>
        </div>
    </form>
{% endblock %}

<!-- 修改Script -->
{% block js %}
    <script>
        // 入口函数
        $(function () {
         $('#btnSMS').click(function () {
                //发起Ajax请求
                $.ajax({
                    url: "{% url 'sms_send' %}",
                    method: 'post',
                    data: {
                        mobile_phone: $('#id_mobile_phone').val(),
                        tpl: "register",
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    },
                    dataType: 'json',
                    success: function (res) {
                        console.log(res);
                        //如果status == True ,倒计时
                        if (res.status) {
                            btnSmsTimeCountDown();
                        } else {

                            $.each(res.errors, function (key,value) {
                                $('#id_'+key).next().text(value[0]);
                            });

                        }
                    }
                })

            });

            // =============响应用户注册的按钮事件================
            $('#btnSubmit').click(function () {
                //======清除之前的所有错误展示=====
                $('.error_msg').empty();
                // ====Ajax====
                $.ajax({
                    url:"{% url 'register' %}",
                    method: "post",
                    data: $('#regForm').serialize(),
                    dataType: "json",
                    success: function (res) {
                        console.log(res);
                        if (res.status){
                            alert("账号注册成功！");
                            //跳转到登录页面
                            location.href = res.url;
                        } else {
                            //遍历错误
                            $.each(res.errors, function (key,value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
    // ============ 响应发送短信按钮的事件 ==============

        });

        // ===============实现按钮上的倒计时==============
        function btnSmsTimeCountDown() {
            //获取倒计时按钮对象
            let btnSms = $('#btnSMS');
            //让按钮禁用
            btnSms.attr('disabled', true);
            //定义一个倒计时的时间
            let time = 59;
            // 使用JS在页面反复执行
            let timeCountDown = setInterval(function () {
                //在按钮上显示倒计时的时间
                btnSms.attr('value', time + '秒后重新获取验证码');
                // time - 1
                time -= 1;
                //判断倒计时有没有结束
                if (time < 0) {
                    // 让倒计时停止
                    clearInterval(timeCountDown);
                    //把按钮启用，并且显示正确的文本
                    btnSms.attr('disabled', false).val('点击获取验证码');
                }

            }, 1000)
        }
    </script>
{% endblock %}

apps/web/templates/register01.html
{% extends 'layout/base01.html' %}


<!--
继承模板后需要修改的地方:
1. 标题
2. 内容 --- 表单
3. 样式 ---- CSS
4. Script --- 事件
-->

<!-- 添加自己页面的内容 -->
<!-- 修改标题 -->
{% block title %}
    用户注册
{% endblock %}

<!-- 修改样式 -->
{% block css %}
    <style>
        #regForm {
            width: 500px;
            margin: 40px auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }
    </style>
{% endblock %}

<!-- 修改内容 -->
{% block content %}
    <form id="regForm">
        <h1 style="text-align: center">用户注册</h1>
        <hr>
        <div class="form-group">
            <label for="id_login">登录名：</label>
            <input type="text" class="form-control" id="id_login" placeholder="请输入登陆名">
        </div>
        <div class="form-group">
            <label for="id_username">用户名：</label>
            <input type="text" class="form-control" id="id_username" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="id_password">密码：</label>
            <input type="password" class="form-control" id="id_password" placeholder="请输入密码">
        </div>
        <div class="form-group">
            <label for="id_re_password">确认密码：</label>
            <input type="password" class="form-control" id="id_re_password" placeholder="请再次输入密码">
        </div>
        <div class="form-group">
            <label for="id_email">邮箱：</label>
            <input type="email" class="form-control" id="id_email" placeholder="请输入邮箱">
        </div>
        <div class="form-group">
            <label for="id_mobile_phone">手机号码：</label>
            <input type="text" class="form-control" id="id_mobile_phone" placeholder="请输入手机号码">
        </div>
        <div class="form-group">
            <label for="id_code">验证码：</label>
            <div class="clearfix">
                <div class="col-md-6" style="padding-left: 0">
                    <input type="text" class="form-control" id="id_code" placeholder="请输入验证码">
                </div>
                <div class="col-md-6">
                    <input type="button" class="btn btn-success" id="btn01" value="点击获取验证码">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 120px">注册</button>
    </form>
{% endblock %}

<!-- 修改Script -->
{% block js %}
{% endblock %}

apps/web/templates/resetpassword.html
{% extends 'layout/base01.html' %}


<!--
继承模板后需要修改的地方:
1. 标题
2. 内容 --- 表单
3. 样式 ---- CSS
4. Script --- 事件
-->

<!-- 添加自己页面的内容 -->
<!-- 修改标题 -->
{% block title %}
    重置密码
{% endblock %}

<!-- 修改样式 -->
{% block css %}
    <style>
        #resetPassword {
            width: 500px;
            margin: 180px auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            padding: 30px;
            border-radius: 20px;
        }

        .error_msg {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

<!-- 修改内容 -->
{% block content %}
    <div id="resetPassword">
        <h1 style="text-align: center">重置密码</h1>
        <hr>
        <form id="resetPasswordForm_Step1">
            {% csrf_token %}
            <!-- 进度条 -->
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"
                     style="width: 33%;">
                    步骤一: 验证码校验
                </div>
            </div>
            <!--表单部分：前两个字段 -->

            {% for field in form %}

                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0">
                                {{ field }}
                                <span class="error_msg"></span>
                            </div>
                            <div class="col-md-6">
                                <input id="btnSMS" type="button" class="btn btn-success" value="点击获取验证码"
                                       style="width: 200px;">
                            </div>
                        </div>

                    </div>
                {% elif field.name == 'mobile_phone' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                        <span class="error_msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <input id="btnStep1" type="button" class="btn btn-primary" style="width: 120px;margin-top: 20px;"
                   value="下一步">
        </form>
        <form id="resetPasswordForm_Step2" style="display:none;">
            <!-- 进度条 -->
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"
                     style="width: 66%;">
                    步骤二: 输入新密码
                </div>
            </div>
            <!--表单部分：密码 -->
            {% for field in form %}

                {% if field.name == 'password' or field.name == 're_password' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                        <span class="error_msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <input id="btnStep2" type="button" class="btn btn-primary" style="width: 120px;margin-top: 20px;"
                   value="确认修改">
        </form>
        <form id="resetPasswordForm_Step3" style="display:none;">
            <!-- 进度条 -->
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"
                     style="width: 100%;">
                    步骤三: 完成修改
                </div>
            </div>
            <!-- 提示成功 -->
            <div style="text-align: center;margin: 60px">
                <span class="glyphicon glyphicon-ok" aria-hidden="true" style="color:green;font-size:30px"></span>
                <span style="font-size:18px;font-weight: bold">密码修改成功！</span>
            </div>
        </form>
        <div style="margin-top: 20px">
            <a href="{% url 'login' %}">账号登陆？</a>
            <a href="{% url 'sms_login' %}" style="margin-left: 10px">验证码登陆？</a>
            <a href="{% url 'register' %}" style="margin-left: 10px">账号注册？</a>
        </div>
    </div>

{% endblock %}

<!-- 修改Script -->
{% block js %}
    <script>
        $(function () {
            // =========发送短信验证码==========
            $('#btnSMS').click(function () {
                //清除错误
                $('.error_msg').empty();

                //===ajax请求====
                $.ajax({
                    url: "{% url 'sms_send' %}",
                    method: 'post',
                    data: {
                        mobile_phone: $('#id_mobile_phone').val(),
                        tpl: 'reset',
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                    },
                    dataType: 'json',
                    success: function (res) {
                        console.log(res);
                        if (res.status) {
                            //倒计时
                            btnSmsTimeCountDown();
                        } else {
                            //展示错误
                            $.each(res.errors, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            });

                        }
                    }
                })
            });


            // ======= 点击第一个表单的按钮 ========
            $('#btnStep1').click(function () {
                // 清除所有的错误
                $('.error_msg').empty();
                //---ajax请求---
                $.ajax({
                    url: "{% url 'resetpassword' %}",
                    method: "post",
                    data: $('#resetPasswordForm_Step1').serialize(),
                    dataType: 'json',
                    success: function (res) {
                        //输出
                        console.log(res);
                        //判断
                        if (res.status) {
                            //resetPasswordForm_Step1 隐藏
                            $('#resetPasswordForm_Step1').css('display', 'none');
                            //resetPasswordForm_Step2 显示
                            $('#resetPasswordForm_Step2').css('display', 'block');
                        } else {
                            $.each(res.errors, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                });


            });


            // ======= 点击第二个表单的按钮 ========
            $('#btnStep2').click(function () {
                //重置所有的错误
                $('.error_msg').empty();
                //不允许password字段
                if ($('#id_password').val() === "") {
                    //展示错误
                    $('#id_password').next().text("密码不能为空！");
                } else {
                    //Ajax请求
                    $.ajax({
                        url: "{% url 'resetpassword' %}",
                        method: 'post',
                        data: {
                            mobile_phone: $('#id_mobile_phone').val(),
                            password: $('#id_password').val(),
                            re_password: $('#id_re_password').val(),
                            csrfmiddlewaretoken: "{{ csrf_token }}"
                        },
                        dataType: 'json',
                        success: function (res) {
                            console.log(res);
                            if (res.status) {
                                //resetPasswordForm_Step2 隐藏
                                $('#resetPasswordForm_Step2').css('display', 'none');
                                //resetPasswordForm_Step3 显示
                                $('#resetPasswordForm_Step3').css('display', 'block');
                            } else {
                                $.each(res.errors, function (key,value) {
                                    $('#id_'+ key).next().text(value[0]);
                                })
                            }
                        }
                    });

                }

            });
        })
        ;

        // ===============实现按钮上的倒计时==============
        function btnSmsTimeCountDown() {
            //获取倒计时按钮对象
            let btnSms = $('#btnSMS');
            //让按钮禁用
            btnSms.attr('disabled', true);
            //定义一个倒计时的时间
            let time = 59;
            // 使用JS在页面反复执行
            let timeCountDown = setInterval(function () {
                //在按钮上显示倒计时的时间
                btnSms.attr('value', time + '秒后重新获取验证码');
                // time - 1
                time -= 1;
                //判断倒计时有没有结束
                if (time < 0) {
                    // 让倒计时停止
                    clearInterval(timeCountDown);
                    //把按钮启用，并且显示正确的文本
                    btnSms.attr('disabled', false).val('点击获取验证码');
                }

            }, 1000)
        }
    </script>

{% endblock %}